# title: Omer Sany Prakash
# logo: images/cropped_profile_image.png
# theme: jekyll-theme-minimal

author:
  name: "Omer Sany Prakash"
  avatar: "/images/profile-round.png"
  links:
    - label: "ðŸ“„ Resume"
      icon: "fas fa-file-pdf"
      url: "/files/Omer_Sany_Resume.pdf"
